%global forgeurl https://github.com/stripe/stripe-cli
%global goipath  github.com/stripe/stripe-cli

# Built with plain `go build` rather than Fedora's go-rpm-macros, so there is
# no build-id note for debugedit to hang debuginfo off. Skip the subpackage.
%global debug_package %{nil}

Name:           stripe-cli
Version:        1.53.1
Release:        1%{?dist}
Summary:        Command-line tool for building, testing and managing Stripe integrations

License:        Apache-2.0
URL:            https://docs.stripe.com/stripe-cli
Source0:        %{forgeurl}/archive/v%{version}/%{name}-%{version}.tar.gz

BuildRequires:  golang
# go.mod declares a minimum Go version; if upstream moves past what Fedora
# ships, GOTOOLCHAIN=auto (set in %%build) fetches the matching toolchain.

%description
The Stripe CLI helps you build, test and manage your Stripe integration from
the terminal. It can forward webhook events to a local server, trigger test
events, tail API request logs, and make authenticated calls to any Stripe API
resource.

%prep
%autosetup -n %{name}-%{version}

%build
# Modules (and, if needed, a newer toolchain) are fetched from the network
# during the build, which COPR's buildroots permit.
export GOPATH="%{_builddir}/.go"
export GOMODCACHE="%{_builddir}/.go/pkg/mod"
export GOCACHE="%{_builddir}/.cache/go-build"
export GOTOOLCHAIN=auto
# Matches upstream's goreleaser config: static binary, version stamped in.
# The generated resource commands are committed upstream, so no
# `go generate` step is needed.
export CGO_ENABLED=0
go build -trimpath -mod=readonly \
  -ldflags "-s -w -X %{goipath}/pkg/version.Version=%{version}" \
  -o stripe ./cmd/stripe

%install
install -Dpm0755 stripe %{buildroot}%{_bindir}/stripe

# Shell completions, generated by the binary we just built.
install -d %{buildroot}%{_datadir}/bash-completion/completions
./stripe completion --shell bash --write-to-stdout > %{buildroot}%{_datadir}/bash-completion/completions/stripe

install -d %{buildroot}%{_datadir}/zsh/site-functions
./stripe completion --shell zsh --write-to-stdout > %{buildroot}%{_datadir}/zsh/site-functions/_stripe

install -d %{buildroot}%{_datadir}/fish/vendor_completions.d
./stripe completion --shell fish --write-to-stdout > %{buildroot}%{_datadir}/fish/vendor_completions.d/stripe.fish

%check
./stripe version

%files
%license LICENSE
%doc README.md
%{_bindir}/stripe
%{_datadir}/bash-completion/completions/stripe
%{_datadir}/zsh/site-functions/_stripe
%{_datadir}/fish/vendor_completions.d/stripe.fish

%changelog
* Thu Oct 08 2026 Dexxiez <toby@boulton.net.au> - 1.53.1-1
- Update to 1.53.1

* Thu Oct 01 2026 Dexxiez <toby@boulton.net.au> - 1.53.0-1
- Update to 1.53.0

* Thu Oct 01 2026 Dexxiez <toby@boulton.net.au> - 1.52.2-1
- Initial package
